name: Validate code quality

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [backend, frontend]
    env:
      JWT_SECRET: "dummy-secret-for-ci"
      BACKEND_URL: "https://example.com/api"
      API_SECRET_KEY: "dummy-api-key-for-ci"
      NEXT_PUBLIC_URL: "https://example.com"
      NEXT_PUBLIC_XMTP_ENV: "dev"
      NEXT_PUBLIC_ENCRYPTION_KEY: "dummy-encryption-key-for-ci"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: "${{ matrix.folder }}/.node-version"
          cache: "yarn"
          cache-dependency-path: "${{ matrix.folder }}/yarn.lock"
        env:
          SKIP_YARN_COREPACK_CHECK: "1"
      - run: corepack enable
      - name: Install dependencies
        working-directory: ${{ matrix.folder }}
        run: yarn
      - name: Format code
        working-directory: ${{ matrix.folder }}
        run: yarn format
      - name: Build code
        working-directory: ${{ matrix.folder }}
        run: yarn build
      - name: Lint
        working-directory: ${{ matrix.folder }}
        run: yarn lint
